apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: danstaken/smithe-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: PIDGTM_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: PIDGTM_DATABASE_URL
          - name: STARTGG_TOKEN
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: STARTGG_TOKEN
      nodeSelector:
        node: rpileaf02