# Use Nginx as the base image
FROM nginx:alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the Nginx configuration file from your local frontend/nginx.conf to the container's Nginx conf directory
COPY frontend/nginx.conf /etc/nginx/conf.d/

# Copy the dist folder from your local frontend/dist to the container's Nginx html directory
COPY frontend/dist/ /usr/share/nginx/html/
