FROM debian:bookworm-slim

# Set the working directory in the container
WORKDIR /usr/src/smithereens

# Install the necessary library
RUN apt-get update && apt-get install -y libpq5 openssl

# Copy only the smithe_backend binary
COPY target/x86_64-unknown-linux-gnu/release/smithe_backend .

# Set the environment variable
ENV ROCKET_ADDRESS=0.0.0.0

# Specify the command to run the binary
CMD ["./smithe_backend"]
