FROM debian:bookworm-slim

# Set the working directory in the container
WORKDIR /usr/src/smithereens

# Copy only the smithe_backend binary
COPY target/aarch64-unknown-linux-gnu/release/smithe_backend .

# Specify the command to run the binary
CMD ["./smithe_backend"]
