version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SMITHE_STARTGG_TOKEN=Bearer ${STARTGG_TOKEN}
      - SMITHE_CLIENT_VERSION=20
      - SMITHE_PORT=3000
    networks:
      - smithereens
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=/api
    networks:
      - smithereens
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  smithereens:
    driver: bridge