FROM debian:buster-slim

# Install necessary packages including PostgreSQL client libraries
# and CA certificates
RUN apt-get update && \
    apt-get install -y libpq5 ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Copy the pidgtm binary and set permissions
COPY --chmod=755 target/x86_64-unknown-linux-gnu/release/pidgtm /usr/local/bin/pidgtm

ENTRYPOINT ["pidgtm"]
