FROM rust:latest

# Set the working directory in the container
WORKDIR /usr/src/smithereens

# Set proper profile
ENV ROCKET_PROFILE=release

# Copy the entire workspace
COPY . .

# Build the project
RUN cargo build --release --package smithe_backend

# Specify the command to run the binary
CMD ["./target/release/smithe_backend"]