FROM rust:latest 

RUN apt-get update && \
    apt-get install -y --no-install-recommends g++-aarch64-linux-gnu libc6-dev-arm64-cross && \
    apt-get install -y crossbuild-essential-arm64 libssl-dev:arm64 && \
    rustup target add aarch64-unknown-linux-gnu 

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
#ENV SERVER_ADDRESS
#ENV SERVER_ADDRESS_2
#ENV RECAPTCHA_SITE_KEY