apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pidgtm-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pidgtm
  template:
    metadata:
      labels:
        app: pidgtm
    spec:
      containers:
        - name: pidgtm
          image: danstaken/pidgtm:latest
          imagePullPolicy: Always
          args: ["map"]
          env:
            - name: STARTGG_TOKEN
              value: "<your-token-here>"
            - name: STARTGG_TOKEN_1
              value: "<your-token-here>"
            - name: STARTGG_TOKEN_2
              value: "<your-token-here>"
            - name: STARTGG_TOKEN_3
              value: "<your-token-here>"
            - name: STARTGG_TOKEN_4
              value: "<your-token-here>"
            - name: STARTGG_TOKEN_5
              value: "<your-token-here>"
            - name: STARTGG_TOKEN_6
              value: "<your-token-here>"
            - name: PIDGTM_DATABASE_URL
              value: "<database-url-here>"
