apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smithe-net-certificate
  namespace: default
spec:
  secretName: smithe-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: smithe.net
  dnsNames:
  - smithe.net