[package]
name = "startgg"
version = "0.1.0"
edition = "2021"
authors = [ "Dan Chiarlone" ]

[lib]
doctest = false

[dependencies]
anyhow = "1"
gql_client = "1"
serde = "1"
as-any = "0.3"
tokio = { version = "1.1", features = ["full"] }