name: Docker Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-binary-x86_64-unknown-linux-gnu

      - name: Build Docker image
        run: |
          docker build -t pidgtm-user-updater:latest -f Dockerfile-UserUpdater .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push pidgtm-user-updater:latest
