name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pidgtm-x86_64-unknown-linux-gnu

      - name: Build Docker image
        run: |
          docker build -t pidgtm-user-updater:latest -f Dockerfile-UserUpdater .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push pidgtm-user-updater:latest
